import { useEffect, useState } from 'react'
import { Package, AlertTriangle, Wallet, ArrowLeftRight } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend } from 'recharts'
import { Box, Card, CardContent, Grid, List, ListItem, Stack, Typography } from '@mui/material'
import { supabase } from '../lib/supabase'
import StatCard from '../components/StatCard'
const PIE_COLORS = ['#2f7d58', '#c1622e', '#c9932f', '#7fc099', '#b1483f', '#4d9f75']
export default function Dashboard() {
  const [loading, setLoading] = useState(true); const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [transactions, setTransactions] = useState([])
  useEffect(() => { (async () => { setLoading(true); const [{ data: p }, { data: c }, { data: t }] = await Promise.all([supabase.from('products').select('*, categories(name)'), supabase.from('categories').select('*'), supabase.from('stock_transactions').select('*, products(name)').order('created_at', { ascending: false }).limit(8)]); setProducts(p || []); setCategories(c || []); setTransactions(t || []); setLoading(false) })() }, [])
  const totalItems = products.reduce((sum, p) => sum + p.quantity, 0); const totalValue = products.reduce((sum, p) => sum + p.quantity * Number(p.unit_price || 0), 0); const lowStock = products.filter((p) => p.quantity <= p.reorder_level)
  const categoryData = categories.map((c) => ({ name: c.name, value: products.filter((p) => p.category_id === c.id).reduce((s, p) => s + p.quantity, 0) })).filter((c) => c.value > 0)
  const topProducts = [...products].sort((a, b) => b.quantity * b.unit_price - a.quantity * a.unit_price).slice(0, 6).map((p) => ({ name: p.name.length > 14 ? `${p.name.slice(0, 14)}…` : p.name, value: p.quantity }))
  const cardSx = { height: '100%' }
  return <Box><Typography variant="h4">Dashboard</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5, mb: 3 }}>Live overview of stock levels, value, and recent movement.</Typography>
    <Grid container spacing={2} sx={{ mb: 2 }}><Grid item xs={12} sm={6} lg={3}><StatCard label="Total SKUs" value={loading ? '—' : products.length} icon={Package} /></Grid><Grid item xs={12} sm={6} lg={3}><StatCard label="Units in stock" value={loading ? '—' : totalItems.toLocaleString()} icon={ArrowLeftRight} /></Grid><Grid item xs={12} sm={6} lg={3}><StatCard label="Inventory value" value={loading ? '—' : `₹${totalValue.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`} icon={Wallet} accent="amber" /></Grid><Grid item xs={12} sm={6} lg={3}><StatCard label="Low stock alerts" value={loading ? '—' : lowStock.length} icon={AlertTriangle} accent={lowStock.length ? 'rose' : 'brand'} hint={lowStock.length ? 'Needs reordering' : 'All good'} /></Grid></Grid>
    <Grid container spacing={2} sx={{ mb: 2 }}><Grid item xs={12} lg={7}><Card sx={cardSx}><CardContent><Typography variant="h6" sx={{ mb: 2 }}>Top products by value</Typography><ResponsiveContainer width="100%" height={260}><BarChart data={topProducts} margin={{ left: -20 }}><CartesianGrid strokeDasharray="3 3" stroke="#dfe3d8" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11, fill: '#12241f99' }} axisLine={{ stroke: '#dfe3d8' }} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: '#12241f99' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ borderRadius: 10, border: '1px solid #dfe3d8', fontSize: 13 }} /><Bar dataKey="value" fill="#2f7d58" radius={[6, 6, 0, 0]} name="Units" /></BarChart></ResponsiveContainer></CardContent></Card></Grid><Grid item xs={12} lg={5}><Card sx={cardSx}><CardContent><Typography variant="h6" sx={{ mb: 2 }}>Stock by category</Typography>{categoryData.length === 0 ? <Typography color="text.secondary" align="center" sx={{ py: 8 }}>No category data yet.</Typography> : <ResponsiveContainer width="100%" height={260}><PieChart><Pie data={categoryData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={85} paddingAngle={2}>{categoryData.map((_, i) => <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />)}</Pie><Tooltip /><Legend wrapperStyle={{ fontSize: 12 }} /></PieChart></ResponsiveContainer>}</CardContent></Card></Grid></Grid>
    <Grid container spacing={2}><Grid item xs={12} lg={6}><Card sx={cardSx}><CardContent><Typography variant="h6" sx={{ mb: 1 }}>Low stock items</Typography>{lowStock.length === 0 ? <Typography color="text.secondary" align="center" sx={{ py: 3 }}>Nothing below reorder level.</Typography> : <List disablePadding>{lowStock.slice(0, 6).map((p) => <ListItem key={p.id} divider sx={{ justifyContent: 'space-between', px: 0 }}><Typography variant="body2">{p.name}</Typography><Typography variant="body2" color="error.main" fontWeight={600}>{p.quantity} left</Typography></ListItem>)}</List>}</CardContent></Card></Grid><Grid item xs={12} lg={6}><Card sx={cardSx}><CardContent><Typography variant="h6" sx={{ mb: 1 }}>Recent movements</Typography>{transactions.length === 0 ? <Typography color="text.secondary" align="center" sx={{ py: 3 }}>No stock movements recorded yet.</Typography> : <List disablePadding>{transactions.map((t) => <ListItem key={t.id} divider sx={{ justifyContent: 'space-between', px: 0 }}><Typography variant="body2">{t.products?.name || 'Unknown product'}</Typography><Typography variant="body2" color={t.type === 'out' ? 'error.main' : 'primary.main'} fontWeight={600}>{t.type === 'out' ? '-' : '+'}{t.quantity}</Typography></ListItem>)}</List>}</CardContent></Card></Grid></Grid>
  </Box>
}
