import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Boxes } from 'lucide-react'
import { Turnstile } from '@marsidev/react-turnstile'
import toast from 'react-hot-toast'
import { Box, Button, Card, CardContent, Divider, Stack, TextField, Typography } from '@mui/material'
import { useAuth } from '../context/AuthContext'
import { sanitizeEmail, validateEmail } from '../lib/inputValidation'
const SITE_KEY = import.meta.env.VITE_TURNSTILE_SITE_KEY
export default function Login() {
  const { session, loading, sendLoginLink, sendAccountCreationLink, signInWithGoogle, getMfaAssurance } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [captchaToken, setCaptchaToken] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { if (loading) return; if (session) (async () => { try { const { data, error } = await getMfaAssurance(); if (error) { navigate('/', { replace: true }); return }; navigate(data?.currentLevel === 'aal1' && data?.nextLevel === 'aal2' ? '/mfa' : '/', { replace: true }) } catch { navigate('/', { replace: true }) } })() }, [session, loading, getMfaAssurance, navigate])
  const handleSubmit = async (e) => { e.preventDefault(); const normalizedEmail = sanitizeEmail(email); const emailError = validateEmail(normalizedEmail); if (emailError) { toast.error(emailError); return }; if (!captchaToken) { toast.error('Please complete the security check.'); return }; setBusy(true); setMessage(''); const { error } = await sendLoginLink(normalizedEmail, captchaToken); if (!error) { setMessage('If an account exists for this email, a login link has been sent to it.'); setBusy(false); return }; const { error: createError } = await sendAccountCreationLink(normalizedEmail, '', captchaToken); setBusy(false); if (createError) toast.error(error.message); else setMessage('If an account exists, a login link was sent. If you are new, a secure account-creation link was sent to this email.') }
  const handleGoogle = async () => { setBusy(true); const { error } = await signInWithGoogle(); if (error) { setBusy(false); toast.error(error.message) } }
  return <AuthFrame><Typography variant="h5">Sign in</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>Enter your email and we'll send a secure sign-in link.</Typography><Box component="form" onSubmit={handleSubmit}><Stack spacing={2}><TextField type="email" required label="Email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" fullWidth />{SITE_KEY ? <Turnstile siteKey={SITE_KEY} onSuccess={setCaptchaToken} onExpire={() => setCaptchaToken('')} onError={() => setCaptchaToken('')} /> : <Typography variant="caption" color="warning.dark">Turnstile site key is not configured.</Typography>}<Button type="submit" disabled={busy || !SITE_KEY} variant="contained" fullWidth>{busy ? 'Sending…' : 'Send sign-in link'}</Button></Stack></Box>{message && <Typography variant="body2" sx={{ mt: 2, p: 1.5, bgcolor: '#eef7f1', border: 1, borderColor: '#d7ecdd', borderRadius: 1, color: 'primary.dark' }}>{message}</Typography>}<Typography variant="body2" align="center" sx={{ mt: 2 }}><Link to="/forgot-password" style={{ color: '#2f7d58', fontWeight: 600 }}>Forgot password?</Link></Typography><Divider sx={{ my: 2.5 }}>OR</Divider><Button onClick={handleGoogle} disabled={busy} variant="outlined" fullWidth>Continue with Google</Button></AuthFrame>
}
export function AuthFrame({ children }) { return <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', alignItems: 'center', justifyContent: 'center', px: 2 }}><Box sx={{ width: '100%', maxWidth: 400 }}><Stack direction="row" justifyContent="center" alignItems="center" spacing={1} sx={{ mb: 4 }}><Box sx={{ width: 40, height: 40, borderRadius: 1, bgcolor: 'primary.main', color: 'primary.contrastText', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Boxes size={20} /></Box><Typography variant="h4">Stockroom</Typography></Stack><Card><CardContent sx={{ p: 4 }}>{children}</CardContent></Card><Typography variant="body2" color="text.secondary" align="center" sx={{ mt: 3 }}>New to Stockroom? <Link to="/signup" style={{ color: '#2f7d58', fontWeight: 600 }}>Create an account</Link></Typography></Box></Box> }
