import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, ShieldCheck } from 'lucide-react'
import toast from 'react-hot-toast'
import { Box, Button, Card, CardContent, Stack, TextField, Typography } from '@mui/material'
import { useAuth } from '../context/AuthContext'
export default function MFA() {
  const { session, listMfaFactors, enrollMfa, challengeMfa, verifyMfa, signOut } = useAuth(); const navigate = useNavigate(); const [factor, setFactor] = useState(null); const [qrCode, setQrCode] = useState(''); const [secret, setSecret] = useState(''); const [code, setCode] = useState(''); const [challengeId, setChallengeId] = useState(''); const [mode, setMode] = useState('loading'); const [busy, setBusy] = useState(false)
  useEffect(() => { (async () => { if (!session) { navigate('/login', { replace: true }); return }; const { data, error } = await listMfaFactors(); if (error) { toast.error(error.message); setMode('error'); return }; const verified = data?.totp?.find((item) => item.status === 'verified'); if (verified) { setFactor(verified); const { data: challenge, error: challengeError } = await challengeMfa(verified.id); if (challengeError) { toast.error(challengeError.message); setMode('error'); return }; setChallengeId(challenge.id); setMode('challenge') } else { const { data: enrolled, error: enrollError } = await enrollMfa(); if (enrollError) { toast.error(enrollError.message); setMode('error'); return }; setFactor(enrolled); setQrCode(enrolled.totp.qr_code); setSecret(enrolled.totp.secret); setMode('enroll') } })() }, [session, navigate, listMfaFactors, enrollMfa, challengeMfa])
  const handleVerify = async (e) => { e.preventDefault(); setBusy(true); let currentChallengeId = challengeId; if (!currentChallengeId) { const { data: challenge, error } = await challengeMfa(factor.id); if (error) { setBusy(false); toast.error(error.message); return }; currentChallengeId = challenge.id }; const { error } = await verifyMfa(factor.id, currentChallengeId, code.trim()); setBusy(false); if (error) toast.error(error.message); else { toast.success('MFA verified'); navigate('/', { replace: true }) } }
  if (mode === 'loading') return <Box sx={{ minHeight: '100vh', display: 'flex', justifyContent: 'center', alignItems: 'center', bgcolor: 'background.default' }}>Loading security settings…</Box>
  if (mode === 'error') return <Box sx={{ minHeight: '100vh', display: 'flex', justifyContent: 'center', alignItems: 'center', bgcolor: 'background.default' }}><Button variant="outlined" onClick={signOut}>Sign out</Button></Box>
  return <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', alignItems: 'center', justifyContent: 'center', p: 2 }}><Card sx={{ width: '100%', maxWidth: 560 }}><CardContent sx={{ p: 4 }}><Link to="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, color: '#12241f99', marginBottom: 24 }}><ArrowLeft size={16} /> Back</Link><Stack direction="row" spacing={1.5} alignItems="center" sx={{ mb: 1 }}><ShieldCheck color="#2f7d58" /><Typography variant="h4">Two-factor authentication</Typography></Stack>{mode === 'challenge' ? <><Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>Your account is protected by MFA. Enter the six-digit code from your authenticator app.</Typography><Box component="form" onSubmit={handleVerify}><Stack spacing={2}><TextField autoFocus inputMode="numeric" inputProps={{ pattern: '[0-9]{6}', maxLength: 6 }} required value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} placeholder="000000" fullWidth sx={{ '& input': { textAlign: 'center', letterSpacing: '.35em', fontSize: 18 } }} /><Button type="submit" disabled={busy} variant="contained" fullWidth>{busy ? 'Verifying…' : 'Verify MFA code'}</Button></Stack></Box></> : <><Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>Scan this QR code with an authenticator app, then enter the generated six-digit code to enable MFA.</Typography><Box sx={{ display: 'flex', justifyContent: 'center', mb: 2 }} dangerouslySetInnerHTML={{ __html: qrCode }} /><Typography variant="caption" color="text.secondary">Can't scan? Enter this secret manually:</Typography><Box component="code" sx={{ display: 'block', wordBreak: 'break-all', bgcolor: 'background.default', border: 1, borderColor: 'divider', p: 1.5, my: 1.5, fontSize: 12 }}>{secret}</Box><Box component="form" onSubmit={handleVerify}><Stack spacing={2}><TextField inputMode="numeric" inputProps={{ pattern: '[0-9]{6}', maxLength: 6 }} required value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} placeholder="000000" fullWidth sx={{ '& input': { textAlign: 'center', letterSpacing: '.35em', fontSize: 18 } }} /><Button type="submit" disabled={busy} variant="contained" fullWidth>{busy ? 'Enabling…' : 'Enable MFA'}</Button></Stack></Box></>}</CardContent></Card></Box>
}
