import { useEffect, useMemo, useState } from 'react'
import { Plus, Search, Pencil, Trash2, PackagePlus, PackageMinus } from 'lucide-react'
import toast from 'react-hot-toast'
import { Box, Button, Card, FormControl, Grid, IconButton, InputAdornment, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { supabase } from '../lib/supabase'
import Modal from '../components/Modal'
import ConfirmDialog from '../components/ConfirmDialog'
const emptyForm = { sku: '', name: '', description: '', category_id: '', supplier_id: '', unit_price: '', cost_price: '', quantity: '', reorder_level: '10', location_id: '' }
export default function Products() {
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [suppliers, setSuppliers] = useState([]); const [locations, setLocations] = useState([]); const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const [stockFilter, setStockFilter] = useState('')
  const [modalOpen, setModalOpen] = useState(false); const [editingId, setEditingId] = useState(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState(null); const [deleting, setDeleting] = useState(false); const [stockModal, setStockModal] = useState(null); const [stockQty, setStockQty] = useState(''); const [stockReason, setStockReason] = useState(''); const [stockBusy, setStockBusy] = useState(false)
  const loadAll = async () => { setLoading(true); const [{ data: p }, { data: c }, { data: s }, { data: l }] = await Promise.all([supabase.from('products').select('*, categories(name), suppliers(name)').order('created_at', { ascending: false }), supabase.from('categories').select('*').order('name'), supabase.from('suppliers').select('*').order('name'), supabase.from('locations').select('*').order('name')]); setProducts(p || []); setCategories(c || []); setSuppliers(s || []); setLocations(l || []); setLoading(false) }; useEffect(() => { loadAll() }, [])
  const filtered = useMemo(() => products.filter((p) => { const q = search.toLowerCase(); const matchesSearch = !search || p.name.toLowerCase().includes(q) || p.sku.toLowerCase().includes(q); const matchesCategory = !categoryFilter || p.category_id === categoryFilter; const matchesStock = !stockFilter || (stockFilter === 'low' && p.quantity <= p.reorder_level) || (stockFilter === 'out' && p.quantity === 0) || (stockFilter === 'ok' && p.quantity > p.reorder_level); return matchesSearch && matchesCategory && matchesStock }), [products, search, categoryFilter, stockFilter])
  const openCreate = () => { setEditingId(null); setForm(emptyForm); setModalOpen(true) }; const openEdit = (p) => { setEditingId(p.id); setForm({ sku: p.sku, name: p.name, description: p.description || '', category_id: p.category_id || '', supplier_id: p.supplier_id || '', unit_price: p.unit_price, cost_price: p.cost_price, quantity: p.quantity, reorder_level: p.reorder_level, location_id: p.location_id || '' }); setModalOpen(true) }
  const handleSave = async (e) => { e.preventDefault(); setSaving(true); const payload = { sku: form.sku.trim(), name: form.name.trim(), description: form.description.trim() || null, category_id: form.category_id || null, supplier_id: form.supplier_id || null, unit_price: Number(form.unit_price) || 0, cost_price: Number(form.cost_price) || 0, reorder_level: Number(form.reorder_level) || 0, location_id: form.location_id || null }; if (!editingId) payload.quantity = Number(form.quantity) || 0; const query = editingId ? supabase.from('products').update(payload).eq('id', editingId) : supabase.from('products').insert(payload); const { error } = await query; setSaving(false); if (error) toast.error(error.message); else { toast.success(editingId ? 'Product updated' : 'Product added'); setModalOpen(false); loadAll() } }
  const handleDelete = async () => { setDeleting(true); const { error } = await supabase.from('products').delete().eq('id', deleteTarget.id); setDeleting(false); if (error) toast.error(error.message); else { toast.success('Product deleted'); setDeleteTarget(null); loadAll() } }
  const openStock = (product, type) => { setStockModal({ product, type }); setStockQty(''); setStockReason('') }
  const submitStock = async (e) => { e.preventDefault(); if (!stockQty || Number(stockQty) <= 0) { toast.error('Enter a quantity greater than 0'); return }; setStockBusy(true); const { error } = await supabase.rpc('apply_stock_transaction', { p_product_id: stockModal.product.id, p_type: stockModal.type, p_quantity: Number(stockQty), p_reason: stockReason || null, p_reference_no: null }); setStockBusy(false); if (error) toast.error(error.message); else { toast.success(`Stock ${stockModal.type === 'in' ? 'added' : 'removed'}`); setStockModal(null); loadAll() } }
  const field = (label, value, key, props = {}) => <TextField label={label} value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })} fullWidth size="small" {...props} />
  return <Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="h4">Products</Typography><Typography variant="body2" color="text.secondary">{filtered.length} of {products.length} items</Typography></Box><Button startIcon={<Plus size={16} />} variant="contained" onClick={openCreate}>Add product</Button></Stack>
    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} sx={{ mb: 2 }}><TextField size="small" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by name or SKU…" sx={{ flex: 1 }} InputProps={{ startAdornment: <InputAdornment position="start"><Search size={16} /></InputAdornment> }} /><FormControl size="small" sx={{ minWidth: 170 }}><InputLabel>Category</InputLabel><Select value={categoryFilter} label="Category" onChange={(e) => setCategoryFilter(e.target.value)}><MenuItem value="">All categories</MenuItem>{categories.map((c) => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{ minWidth: 170 }}><InputLabel>Stock level</InputLabel><Select value={stockFilter} label="Stock level" onChange={(e) => setStockFilter(e.target.value)}><MenuItem value="">All stock levels</MenuItem><MenuItem value="ok">In stock</MenuItem><MenuItem value="low">Low stock</MenuItem><MenuItem value="out">Out of stock</MenuItem></Select></FormControl></Stack>
    <TableContainer component={Paper} sx={{ border: 1, borderColor: 'divider', boxShadow: 1 }}><Table size="small"><TableHead><TableRow>{['Product', 'SKU', 'Category', 'Qty', 'Unit price', 'Actions'].map((h) => <TableCell key={h} align={['Qty', 'Unit price', 'Actions'].includes(h) ? 'right' : 'left'} sx={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: 1, color: 'text.secondary', fontWeight: 600 }}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{loading ? <TableRow><TableCell colSpan={6} align="center" sx={{ py: 5 }}>Loading products…</TableCell></TableRow> : filtered.length === 0 ? <TableRow><TableCell colSpan={6} align="center" sx={{ py: 5 }}>No products found. Try adding one.</TableCell></TableRow> : filtered.map((p) => <TableRow key={p.id} hover><TableCell><Typography variant="body2" fontWeight={600}>{p.name}</Typography>{p.suppliers?.name && <Typography variant="caption" color="text.secondary">{p.suppliers.name}</Typography>}</TableCell><TableCell sx={{ fontFamily: 'monospace', fontSize: 12 }} color="text.secondary">{p.sku}</TableCell><TableCell color="text.secondary">{p.categories?.name || '—'}</TableCell><TableCell align="right" sx={{ color: p.quantity <= p.reorder_level ? 'error.main' : 'text.primary', fontWeight: 600 }}>{p.quantity}</TableCell><TableCell align="right" color="text.secondary">₹{Number(p.unit_price).toLocaleString('en-IN')}</TableCell><TableCell align="right"><IconButton title="Stock in" size="small" color="primary" onClick={() => openStock(p, 'in')}><PackagePlus size={16} /></IconButton><IconButton title="Stock out" size="small" color="secondary" onClick={() => openStock(p, 'out')}><PackageMinus size={16} /></IconButton><IconButton title="Edit" size="small" onClick={() => openEdit(p)}><Pencil size={16} /></IconButton><IconButton title="Delete" size="small" color="error" onClick={() => setDeleteTarget(p)}><Trash2 size={16} /></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title={editingId ? 'Edit product' : 'Add product'} size="lg"><Box component="form" onSubmit={handleSave}><Grid container spacing={2}>{[field('SKU', form.sku, 'sku', { required: true }), field('Name', form.name, 'name', { required: true })].map((x, i) => <Grid item xs={12} sm={6} key={i}>{x}</Grid>)}<Grid item xs={12} sm={6}><FormControl fullWidth size="small"><InputLabel>Category</InputLabel><Select label="Category" value={form.category_id} onChange={(e) => setForm({ ...form, category_id: e.target.value })}><MenuItem value="">None</MenuItem>{categories.map((c) => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} sm={6}><FormControl fullWidth size="small"><InputLabel>Supplier</InputLabel><Select label="Supplier" value={form.supplier_id} onChange={(e) => setForm({ ...form, supplier_id: e.target.value })}><MenuItem value="">None</MenuItem>{suppliers.map((s) => <MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</Select></FormControl></Grid>{[['Unit price (₹)', 'unit_price'], ['Cost price (₹)', 'cost_price'], ...(!editingId ? [['Opening quantity', 'quantity']] : []), ['Reorder level', 'reorder_level']].map(([label, key]) => <Grid item xs={12} sm={6} key={key}>{field(label, form[key], key, { type: 'number', inputProps: { min: 0, step: key.includes('price') ? '0.01' : '1' } })}</Grid>)}<Grid item xs={12} sm={6}><FormControl fullWidth size="small"><InputLabel>Location</InputLabel><Select label="Location" value={form.location_id} onChange={(e) => setForm({ ...form, location_id: e.target.value })}><MenuItem value="">None</MenuItem>{locations.map((l) => <MenuItem key={l.id} value={l.id}>{l.name}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12}><TextField label="Description" multiline rows={2} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} fullWidth size="small" /></Grid><Grid item xs={12}><Stack direction="row" spacing={1.5}><Button fullWidth variant="outlined" onClick={() => setModalOpen(false)}>Cancel</Button><Button fullWidth type="submit" variant="contained" disabled={saving}>{saving ? 'Saving…' : editingId ? 'Save changes' : 'Add product'}</Button></Stack></Grid></Grid></Box></Modal>
    <Modal open={!!stockModal} onClose={() => setStockModal(null)} title={stockModal?.type === 'in' ? 'Add stock' : 'Remove stock'} size="sm">{stockModal && <Box component="form" onSubmit={submitStock}><Stack spacing={2}><Typography variant="body2" color="text.secondary">{stockModal.product.name} — currently {stockModal.product.quantity} in stock</Typography><TextField autoFocus required type="number" inputProps={{ min: 1 }} label="Quantity" value={stockQty} onChange={(e) => setStockQty(e.target.value)} fullWidth size="small" /><TextField label="Reason (optional)" value={stockReason} onChange={(e) => setStockReason(e.target.value)} placeholder="e.g. New shipment, damaged goods" fullWidth size="small" /><Stack direction="row" spacing={1.5}><Button fullWidth variant="outlined" onClick={() => setStockModal(null)}>Cancel</Button><Button fullWidth type="submit" variant="contained" color={stockModal.type === 'in' ? 'primary' : 'secondary'} disabled={stockBusy}>{stockBusy ? 'Saving…' : stockModal.type === 'in' ? 'Add stock' : 'Remove stock'}</Button></Stack></Stack></Box>}</Modal>
    <ConfirmDialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} onConfirm={handleDelete} busy={deleting} message={`Delete "${deleteTarget?.name}"? This will also remove its stock movement history.`} />
  </Box>
}
