import { useEffect, useState } from 'react'
import { Download } from 'lucide-react'
import Papa from 'papaparse'
import toast from 'react-hot-toast'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
import { Box, Button, Card, CardContent, Grid, Stack, Typography } from '@mui/material'
import { supabase } from '../lib/supabase'
export default function Reports() {
  const [products, setProducts] = useState([]); const [transactions, setTransactions] = useState([]); const [loading, setLoading] = useState(true)
  useEffect(() => { (async () => { setLoading(true); const [{ data: p }, { data: t }] = await Promise.all([supabase.from('products').select('*, categories(name)'), supabase.from('stock_transactions').select('*').order('created_at', { ascending: true })]); setProducts(p || []); setTransactions(t || []); setLoading(false) })() }, [])
  const exportProductsCSV = () => { if (!products.length) { toast.error('No products to export'); return }; const rows = products.map((p) => ({ SKU: p.sku, Name: p.name, Category: p.categories?.name || '', Quantity: p.quantity, 'Unit Price': p.unit_price, 'Cost Price': p.cost_price, 'Reorder Level': p.reorder_level, 'Stock Value': (p.quantity * Number(p.unit_price)).toFixed(2) })); const csv = Papa.unparse(rows); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `inventory-report-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); toast.success('CSV exported') }
  const dailyTrend = (() => { const map = {}; transactions.forEach((t) => { const day = t.created_at.slice(0, 10); map[day] = (map[day] || 0) + (t.type === 'out' ? -t.quantity : t.quantity) }); return Object.entries(map).slice(-30).map(([date, value]) => ({ date: date.slice(5), value })) })()
  const totalValue = products.reduce((s, p) => s + p.quantity * Number(p.unit_price || 0), 0); const totalCost = products.reduce((s, p) => s + p.quantity * Number(p.cost_price || 0), 0); const potentialProfit = totalValue - totalCost
  return <Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="h4">Reports</Typography><Typography variant="body2" color="text.secondary">Export data and track net stock movement over time.</Typography></Box><Button startIcon={<Download size={16} />} variant="contained" onClick={exportProductsCSV}>Export inventory CSV</Button></Stack>
    <Grid container spacing={2} sx={{ mb: 2 }}>{[['Retail value', totalValue, 'text.primary'], ['Cost value', totalCost, 'text.primary'], ['Potential margin', potentialProfit, 'primary.main']].map(([label, value, color]) => <Grid item xs={12} sm={4} key={label}><Card><CardContent><Typography variant="overline" color="text.secondary">{label}</Typography><Typography variant="h5" color={color}>₹{value.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</Typography></CardContent></Card></Grid>)}</Grid>
    <Card><CardContent><Typography variant="h6" sx={{ mb: 2 }}>Net daily stock movement</Typography>{loading ? <Typography color="text.secondary" align="center" sx={{ py: 8 }}>Loading…</Typography> : dailyTrend.length === 0 ? <Typography color="text.secondary" align="center" sx={{ py: 8 }}>No transactions yet — movement will appear here once you log stock in/out.</Typography> : <ResponsiveContainer width="100%" height={280}><LineChart data={dailyTrend}><CartesianGrid strokeDasharray="3 3" stroke="#dfe3d8" vertical={false} /><XAxis dataKey="date" tick={{ fontSize: 11, fill: '#12241f99' }} axisLine={{ stroke: '#dfe3d8' }} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: '#12241f99' }} axisLine={false} tickLine={false} /><Tooltip /><Line type="monotone" dataKey="value" stroke="#2f7d58" strokeWidth={2.5} dot={false} name="Net units" /></LineChart></ResponsiveContainer>}</CardContent></Card>
  </Box>
}
