import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Turnstile } from '@marsidev/react-turnstile'
import toast from 'react-hot-toast'
import { Box, Button, Divider, Stack, TextField, Typography } from '@mui/material'
import { useAuth } from '../context/AuthContext'
import { sanitizeEmail, sanitizeText, validateEmail, validateFullName, validatePassword } from '../lib/inputValidation'
import { AuthFrame } from './Login'
const SITE_KEY = import.meta.env.VITE_TURNSTILE_SITE_KEY
export default function Signup() {
  const { signUp, signInWithGoogle } = useAuth(); const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [captchaToken, setCaptchaToken] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  const handleSubmit = async (e) => { e.preventDefault(); const normalizedEmail = sanitizeEmail(email); const cleanName = sanitizeText(fullName); const error = validateEmail(normalizedEmail) || validateFullName(cleanName) || validatePassword(password); if (error) { toast.error(error); return }; if (!captchaToken) { toast.error('Please complete the security check.'); return }; setBusy(true); const { error: signUpError } = await signUp(normalizedEmail, password, cleanName, captchaToken); setBusy(false); if (signUpError) toast.error(signUpError.message); else setMessage('Your account creation link has been sent to your email. Open it to finish signing in.') }
  const handleGoogle = async () => { setBusy(true); const { error } = await signInWithGoogle(); if (error) { setBusy(false); toast.error(error.message) } }
  return <AuthFrame><Typography variant="h5">Create your account</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>We'll verify your email before giving you access.</Typography><Box component="form" onSubmit={handleSubmit}><Stack spacing={2}><TextField required label="Full name" value={fullName} onChange={(e) => setFullName(e.target.value)} fullWidth /><TextField type="email" required label="Email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" fullWidth /><TextField type="password" required minLength={8} label="Password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 8 characters" fullWidth />{SITE_KEY ? <Turnstile siteKey={SITE_KEY} onSuccess={setCaptchaToken} onExpire={() => setCaptchaToken('')} onError={() => setCaptchaToken('')} /> : <Typography variant="caption" color="warning.dark">Turnstile site key is not configured.</Typography>}<Button type="submit" disabled={busy || !SITE_KEY} variant="contained" fullWidth>{busy ? 'Creating…' : 'Create account'}</Button></Stack></Box>{message && <Typography variant="body2" sx={{ mt: 2, p: 1.5, bgcolor: '#eef7f1', border: 1, borderColor: '#d7ecdd', borderRadius: 1, color: 'primary.dark' }}>{message}</Typography>}<Divider sx={{ my: 2.5 }}>OR</Divider><Button onClick={handleGoogle} disabled={busy} variant="outlined" fullWidth>Continue with Google</Button><Typography variant="body2" color="text.secondary" align="center" sx={{ mt: 3 }}>Already have an account? <Link to="/login" style={{ color: '#2f7d58', fontWeight: 600 }}>Sign in</Link></Typography></AuthFrame>
}
