import { useEffect, useState } from 'react'
import { Plus, Pencil, Trash2, Truck, Mail, Phone } from 'lucide-react'
import toast from 'react-hot-toast'
import { Box, Button, Card, CardContent, Grid, IconButton, Stack, TextField, Typography } from '@mui/material'
import { supabase } from '../lib/supabase'
import Modal from '../components/Modal'
import ConfirmDialog from '../components/ConfirmDialog'
const empty = { name: '', contact_name: '', email: '', phone: '', address: '' }
export default function Suppliers() {
  const [suppliers, setSuppliers] = useState([]); const [loading, setLoading] = useState(true); const [modalOpen, setModalOpen] = useState(false); const [editingId, setEditingId] = useState(null); const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false); const [deleteTarget, setDeleteTarget] = useState(null); const [deleting, setDeleting] = useState(false)
  const load = async () => { setLoading(true); const { data } = await supabase.from('suppliers').select('*').order('name'); setSuppliers(data || []); setLoading(false) }; useEffect(() => { load() }, [])
  const openCreate = () => { setEditingId(null); setForm(empty); setModalOpen(true) }; const openEdit = (s) => { setEditingId(s.id); setForm({ name: s.name, contact_name: s.contact_name || '', email: s.email || '', phone: s.phone || '', address: s.address || '' }); setModalOpen(true) }
  const handleSave = async (e) => { e.preventDefault(); setSaving(true); const payload = { name: form.name.trim(), contact_name: form.contact_name.trim() || null, email: form.email.trim() || null, phone: form.phone.trim() || null, address: form.address.trim() || null }; const query = editingId ? supabase.from('suppliers').update(payload).eq('id', editingId) : supabase.from('suppliers').insert(payload); const { error } = await query; setSaving(false); if (error) toast.error(error.message); else { toast.success(editingId ? 'Supplier updated' : 'Supplier added'); setModalOpen(false); load() } }
  const handleDelete = async () => { setDeleting(true); const { error } = await supabase.from('suppliers').delete().eq('id', deleteTarget.id); setDeleting(false); if (error) toast.error(error.message); else { toast.success('Supplier deleted'); setDeleteTarget(null); load() } }
  return <Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="h4">Suppliers</Typography><Typography variant="body2" color="text.secondary">Vendors you restock from.</Typography></Box><Button startIcon={<Plus size={16} />} variant="contained" onClick={openCreate}>Add supplier</Button></Stack>
    {loading ? <Typography color="text.secondary">Loading…</Typography> : suppliers.length === 0 ? <Typography color="text.secondary">No suppliers yet.</Typography> : <Grid container spacing={2}>{suppliers.map((s) => <Grid item xs={12} sm={6} lg={4} key={s.id}><Card sx={{ height: '100%' }}><CardContent><Stack direction="row" justifyContent="space-between"><Box sx={{ width: 36, height: 36, borderRadius: 1, bgcolor: 'rgba(193,98,46,.1)', color: 'secondary.main', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Truck size={16} /></Box><Box><IconButton size="small" onClick={() => openEdit(s)}><Pencil size={15} /></IconButton><IconButton size="small" color="error" onClick={() => setDeleteTarget(s)}><Trash2 size={15} /></IconButton></Box></Stack><Typography variant="h6" sx={{ mt: 1.5 }}>{s.name}</Typography>{s.contact_name && <Typography variant="body2" color="text.secondary">{s.contact_name}</Typography>}<Stack spacing={.5} sx={{ mt: 1.5 }}>{s.email && <Typography variant="caption" color="text.secondary" sx={{ display: 'flex', alignItems: 'center', gap: .75 }}><Mail size={12} />{s.email}</Typography>}{s.phone && <Typography variant="caption" color="text.secondary" sx={{ display: 'flex', alignItems: 'center', gap: .75 }}><Phone size={12} />{s.phone}</Typography>}</Stack></CardContent></Card></Grid>)}</Grid>}
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title={editingId ? 'Edit supplier' : 'Add supplier'}><Box component="form" onSubmit={handleSave}><Stack spacing={2}><TextField required label="Company name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} fullWidth /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="Contact person" value={form.contact_name} onChange={(e) => setForm({ ...form, contact_name: e.target.value })} fullWidth /><TextField label="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} fullWidth /></Stack><TextField type="email" label="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} fullWidth /><TextField label="Address" multiline rows={2} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} fullWidth /><Stack direction="row" spacing={1.5}><Button fullWidth variant="outlined" onClick={() => setModalOpen(false)}>Cancel</Button><Button fullWidth type="submit" variant="contained" disabled={saving}>{saving ? 'Saving…' : 'Save'}</Button></Stack></Stack></Box></Modal>
    <ConfirmDialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} onConfirm={handleDelete} busy={deleting} message={`Delete supplier "${deleteTarget?.name}"?`} /></Box>
}
