import { useEffect, useMemo, useState } from 'react'
import { ArrowUpCircle, ArrowDownCircle, RefreshCcw } from 'lucide-react'
import { Box, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material'
import { supabase } from '../lib/supabase'

export default function Transactions() {
  const [transactions, setTransactions] = useState([]); const [loading, setLoading] = useState(true); const [typeFilter, setTypeFilter] = useState('')
  useEffect(() => { (async () => { setLoading(true); const { data } = await supabase.from('stock_transactions').select('*, products(name, sku), profiles(full_name)').order('created_at', { ascending: false }).limit(200); setTransactions(data || []); setLoading(false) })() }, [])
  const filtered = useMemo(() => transactions.filter((t) => !typeFilter || t.type === typeFilter), [transactions, typeFilter])
  const icon = (type) => type === 'in' ? <ArrowUpCircle size={16} color="#2f7d58" /> : type === 'out' ? <ArrowDownCircle size={16} color="#b1483f" /> : <RefreshCcw size={16} color="#c9932f" />
  return <Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="h4">Stock movements</Typography><Typography variant="body2" color="text.secondary">Full audit trail of every stock in/out event.</Typography></Box><FormControl size="small" sx={{ minWidth: 150 }}><InputLabel>Type</InputLabel><Select value={typeFilter} label="Type" onChange={(e) => setTypeFilter(e.target.value)}><MenuItem value="">All types</MenuItem><MenuItem value="in">Stock in</MenuItem><MenuItem value="out">Stock out</MenuItem><MenuItem value="adjustment">Adjustment</MenuItem></Select></FormControl></Stack>
    <TableContainer component={Paper} sx={{ border: 1, borderColor: 'divider', boxShadow: 1 }}><Table size="small"><TableHead><TableRow>{['Type', 'Product', 'Qty', 'Reason', 'By', 'Date'].map((h) => <TableCell key={h} align={h === 'Qty' ? 'right' : 'left'} sx={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: 1, color: 'text.secondary', fontWeight: 600 }}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{loading ? <TableRow><TableCell colSpan={6} align="center" sx={{ py: 5 }}>Loading…</TableCell></TableRow> : filtered.length === 0 ? <TableRow><TableCell colSpan={6} align="center" sx={{ py: 5 }}>No movements recorded yet.</TableCell></TableRow> : filtered.map((t) => <TableRow key={t.id} hover><TableCell><Stack direction="row" alignItems="center" spacing={1} sx={{ textTransform: 'capitalize' }}>{icon(t.type)}{t.type}</Stack></TableCell><TableCell><Typography variant="body2">{t.products?.name || 'Deleted product'}</Typography><Typography variant="caption" color="text.secondary" fontFamily="monospace">{t.products?.sku}</Typography></TableCell><TableCell align="right" sx={{ color: t.type === 'out' ? 'error.main' : 'primary.main', fontWeight: 600 }}>{t.type === 'out' ? '-' : '+'}{t.quantity}</TableCell><TableCell color="text.secondary">{t.reason || '—'}</TableCell><TableCell color="text.secondary">{t.profiles?.full_name || '—'}</TableCell><TableCell color="text.secondary" sx={{ fontSize: 12 }}>{new Date(t.created_at).toLocaleString('en-IN')}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
  </Box>
}
